# --- IDENTIFICATION DU PROJET ---
sonar.projectKey=FALL2000_Eclair-school-1.0.0
sonar.organization=fall2000
sonar.host.url=https://sonarcloud.io

# --- STRUCTURE DU PROJET ---
# On indique que le code est dans ces deux dossiers
sonar.sources=backend, frontend
# On précise les langages pour aider l'analyse
sonar.language=py,ts,js

# --- CONFIGURATION ---
# 1. On exclut TOUT du calcul de couverture pour rester au "Vert"
sonar.coverage.exclusions=**/*

# 2. On exclut les dossiers techniques pour ne pas polluer l'analyse
sonar.exclusions=**/node_modules/**, **/venv/**, **/dist/**, **/build/**, **/*.spec.ts, **/*.test.ts

# --- ENCODAGE ---
sonar.sourceEncoding=UTF-8

# --- OPTIONS SPECIFIQUES (PYTHON & TS) ---
# On désactive la recherche de rapports de tests puisqu'il n'y en a pas
sonar.python.coverage.reportPaths=
sonar.javascript.lcov.reportPath=