"""add_enseignant_id_foreign_key_presence_enseignant

Revision ID: 136b7be96ce5
Revises: 5c7db25559e3
Create Date: 2026-04-27 17:08:39.533351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136b7be96ce5'
down_revision: Union[str, Sequence[str], None] = '5c7db25559e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_user', 'id_role', name='unique_role_user')
    )
    op.create_foreign_key(None, 'classe', 'niveau', ['id_niveau'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cours', 'enseignant', ['id_enseignant'], ['id'])
    op.create_foreign_key(None, 'cours', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'cours', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'cours', 'matiere', ['id_matiere'], ['id'])
    op.create_foreign_key(None, 'cycle', 'section', ['id_section'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discipline_eleve', 'evaluation', ['id_evaluation'], ['id'])
    op.create_foreign_key(None, 'discipline_eleve', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'discipline_eleve', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'discipline_eleve', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'enseignant', 'type_salaire', ['id_type_salaire'], ['id'])
    op.create_foreign_key(None, 'enseignement', 'matiere', ['id_matiere'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enseignement', 'enseignant', ['id_enseignant'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation', 'trimestre', ['id_trimestre'], ['id'])
    op.create_foreign_key(None, 'inscription', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'inscription', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'inscription', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'matiere_evalue', 'niveau', ['id_niveau'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'niveau', 'cycle', ['id_cycle'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'niveau', 'serie', ['id_serie'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notation', 'appreciation', ['id_appreciation'], ['id'])
    op.create_foreign_key(None, 'notation', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'notation', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'notation', 'evaluation', ['id_evaluation'], ['id'])
    op.create_foreign_key(None, 'notation', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'notation', 'matiere_evalue', ['id_matiere_evalue'], ['id'])
    op.create_foreign_key(None, 'permission', 'role', ['id_role'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'presence_eleve', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'presence_eleve', 'cours', ['id_cours'], ['id'])
    op.add_column('presence_enseignant', sa.Column('id_enseignant', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'presence_enseignant', 'enseignant', ['id_enseignant'], ['id'])
    op.create_foreign_key(None, 'presence_enseignant', 'cours', ['id_cours'], ['id'])
    op.create_foreign_key(None, 'reglement', 'tranche_pension', ['id_tranche_pension'], ['id'])
    op.create_foreign_key(None, 'reglement', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'reglement', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'tranche_pension', 'niveau', ['id_niveau'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tranche_pension', type_='foreignkey')
    op.drop_constraint(None, 'reglement', type_='foreignkey')
    op.drop_constraint(None, 'reglement', type_='foreignkey')
    op.drop_constraint(None, 'reglement', type_='foreignkey')
    op.drop_constraint(None, 'presence_enseignant', type_='foreignkey')
    op.drop_constraint(None, 'presence_enseignant', type_='foreignkey')
    op.drop_column('presence_enseignant', 'id_enseignant')
    op.drop_constraint(None, 'presence_eleve', type_='foreignkey')
    op.drop_constraint(None, 'presence_eleve', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'niveau', type_='foreignkey')
    op.drop_constraint(None, 'niveau', type_='foreignkey')
    op.drop_constraint(None, 'matiere_evalue', type_='foreignkey')
    op.drop_constraint(None, 'inscription', type_='foreignkey')
    op.drop_constraint(None, 'inscription', type_='foreignkey')
    op.drop_constraint(None, 'inscription', type_='foreignkey')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_constraint(None, 'enseignement', type_='foreignkey')
    op.drop_constraint(None, 'enseignement', type_='foreignkey')
    op.drop_constraint(None, 'enseignant', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'cycle', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'classe', type_='foreignkey')
    op.drop_table('user_role')
    # ### end Alembic commands ###
