"""initial

Revision ID: 585eb30305ca
Revises: 
Create Date: 2026-03-24 17:51:48.893203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '585eb30305ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annee',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('is_cloture', sa.Boolean(),
                              server_default='0', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('appreciation',
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('valeur_min', sa.Float(), nullable=False),
                    sa.Column('valeur_max', sa.Float(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('eleve',
                    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=True),
                    sa.Column('dat_naissance', sa.Date(), nullable=False),
                    sa.Column('nom_pere', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=True),
                    sa.Column('lieu_naissance', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('nom_mere', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('quartier_residence', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('telephone_parent1', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=False),
                    sa.Column('telephone_parent2', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=True),
                    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(
                        length=1), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('matricule', sqlmodel.sql.sqltypes.AutoString(
                        length=8), nullable=False),
                    sa.Column('is_active', sa.Boolean(),
                              server_default='1', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('matricule')
                    )
    op.create_table('matiere',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('role',
                    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('section',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('serie',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('trimestre',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('type_salaire',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('user',
                    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=True),
                    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(
                        length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('cycle',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_section', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_section'], ['section.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('enseignant',
                    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=False),
                    sa.Column('prenom', sqlmodel.sql.sqltypes.AutoString(
                        length=255), nullable=True),
                    sa.Column('dernier_diplome', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('genre', sqlmodel.sql.sqltypes.AutoString(
                        length=1), nullable=False),
                    sa.Column('telephone1', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('telephone2', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=True),
                    sa.Column('montant_salaire', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(),
                              server_default='1', nullable=False),
                    sa.Column('id_type_salaire', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_type_salaire'], [
                                            'type_salaire.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('evaluation',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('date_deb', sa.Date(), nullable=False),
                    sa.Column('date_fin', sa.Date(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_trimestre', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['id_trimestre'], ['trimestre.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('permission',
                    sa.Column('element_name', sqlmodel.sql.sqltypes.AutoString(
                        length=100), nullable=False),
                    sa.Column('permission_value', sqlmodel.sql.sqltypes.AutoString(
                        length=50), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_role', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_role'], ['role.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('enseignement',
                    sa.Column('unite_salaire_mt', sa.Float(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_enseignant', sa.Integer(), nullable=True),
                    sa.Column('id_matiere', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_enseignant'], ['enseignant.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['id_matiere'], ['matiere.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_enseignant', 'id_matiere',
                                        name='unique_enseignant_matiere')
                    )
    op.create_table('niveau',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('montant_inscription',
                              sa.Float(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_cycle', sa.Integer(), nullable=True),
                    sa.Column('id_serie', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_cycle'], ['cycle.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['id_serie'], ['serie.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('classe',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_niveau', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_niveau'], ['niveau.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('matiere_evalue',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(
                        length=30), nullable=False),
                    sa.Column('coefficient', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_niveau', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_niveau'], ['niveau.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('tranche_pension',
                    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(
                        length=10), nullable=False),
                    sa.Column('libelle', sqlmodel.sql.sqltypes.AutoString(
                        length=60), nullable=False),
                    sa.Column('numero_ordre', sa.Integer(), nullable=False),
                    sa.Column('montant', sa.Float(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_niveau', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_niveau'], ['niveau.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('id_niveau', 'numero_ordre',
                                        name='unique_num_ordre_niveau')
                    )
    op.create_table('cours',
                    sa.Column('jour', sqlmodel.sql.sqltypes.AutoString(
                        length=15), nullable=False),
                    sa.Column('heure_deb', sa.Time(), nullable=False),
                    sa.Column('heure_fin', sa.Time(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_enseignant', sa.Integer(), nullable=False),
                    sa.Column('id_classe', sa.Integer(), nullable=False),
                    sa.Column('id_annee', sa.Integer(), nullable=False),
                    sa.Column('id_matiere', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_annee'], ['annee.id'], ),
                    sa.ForeignKeyConstraint(['id_classe'], ['classe.id'], ),
                    sa.ForeignKeyConstraint(
                        ['id_enseignant'], ['enseignant.id'], ),
                    sa.ForeignKeyConstraint(['id_matiere'], ['matiere.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('discipline_eleve',
                    sa.Column('nb_heure_obtenu', sa.Integer(), nullable=False),
                    sa.Column('nb_heure_justifie',
                              sa.Integer(), nullable=False),
                    sa.Column('nb_heure_total', sa.Integer(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_eleve', sa.Integer(), nullable=False),
                    sa.Column('id_annee', sa.Integer(), nullable=False),
                    sa.Column('id_classe', sa.Integer(), nullable=False),
                    sa.Column('id_evaluation', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_annee'], ['annee.id'], ),
                    sa.ForeignKeyConstraint(['id_classe'], ['classe.id'], ),
                    sa.ForeignKeyConstraint(['id_eleve'], ['eleve.id'], ),
                    sa.ForeignKeyConstraint(
                        ['id_evaluation'], ['evaluation.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_eleve', 'id_annee', 'id_classe',
                                        'id_evaluation', name='unique_eleve_annee_classe_evaluation')
                    )
    op.create_table('inscription',
                    sa.Column('is_redoublant', sa.Boolean(),
                              server_default='0', nullable=False),
                    sa.Column('is_nouveau', sa.Boolean(),
                              server_default='0', nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_eleve', sa.Integer(), nullable=False),
                    sa.Column('id_classe', sa.Integer(), nullable=False),
                    sa.Column('id_annee', sa.Integer(), nullable=False),
                    sa.Column('date_inscris', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['id_annee'], ['annee.id'], ),
                    sa.ForeignKeyConstraint(['id_classe'], ['classe.id'], ),
                    sa.ForeignKeyConstraint(['id_eleve'], ['eleve.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_eleve', 'id_classe', 'id_annee',
                                        name='unique_inscription_eleve_annee')
                    )
    op.create_table('notation',
                    sa.Column('note', sa.Float(), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_matiere_evalue',
                              sa.Integer(), nullable=False),
                    sa.Column('id_eleve', sa.Integer(), nullable=False),
                    sa.Column('id_annee', sa.Integer(), nullable=False),
                    sa.Column('id_evaluation', sa.Integer(), nullable=False),
                    sa.Column('id_appreciation', sa.Integer(), nullable=False),
                    sa.Column('id_classe', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_annee'], ['annee.id'], ),
                    sa.ForeignKeyConstraint(['id_appreciation'], [
                                            'appreciation.id'], ),
                    sa.ForeignKeyConstraint(['id_classe'], ['classe.id'], ),
                    sa.ForeignKeyConstraint(['id_eleve'], ['eleve.id'], ),
                    sa.ForeignKeyConstraint(
                        ['id_evaluation'], ['evaluation.id'], ),
                    sa.ForeignKeyConstraint(['id_matiere_evalue'], [
                        'matiere_evalue.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_matiere_evalue', 'id_eleve', 'id_annee', 'id_evaluation',
                                        'id_classe', name='unique_matiere_evalue_eleve_annee_classe')
                    )
    op.create_table('reglement',
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(
                        length=20), nullable=False),
                    sa.Column('montant', sa.Float(), nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_tranche_pension',
                              sa.Integer(), nullable=False),
                    sa.Column('id_eleve', sa.Integer(), nullable=False),
                    sa.Column('id_annee', sa.Integer(), nullable=False),
                    sa.Column('date_reglement', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['id_annee'], ['annee.id'], ),
                    sa.ForeignKeyConstraint(['id_eleve'], ['eleve.id'], ),
                    sa.ForeignKeyConstraint(['id_tranche_pension'], [
                        'tranche_pension.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('presence_eleve',
                    sa.Column('date_cours', sa.Date(), nullable=False),
                    sa.Column('is_present', sa.Boolean(),
                              server_default='1', nullable=False),
                    sa.Column('is_justifie', sa.Boolean(),
                              server_default='0', nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_cours', sa.Integer(), nullable=False),
                    sa.Column('id_eleve', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_cours'], ['cours.id'], ),
                    sa.ForeignKeyConstraint(['id_eleve'], ['eleve.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_cours', 'id_eleve',
                                        'date_cours', name='unique_cours_eleve_date')
                    )
    op.create_table('presence_enseignant',
                    sa.Column('date_cours', sa.Date(), nullable=False),
                    sa.Column('is_present', sa.Boolean(),
                              server_default='1', nullable=False),
                    sa.Column('is_justifie', sa.Boolean(),
                              server_default='0', nullable=False),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_cours', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id_cours'], ['cours.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presence_enseignant')
    op.drop_table('presence_eleve')
    op.drop_table('reglement')
    op.drop_table('notation')
    op.drop_table('inscription')
    op.drop_table('discipline_eleve')
    op.drop_table('cours')
    op.drop_table('tranche_pension')
    op.drop_table('matiere_evalue')
    op.drop_table('classe')
    op.drop_table('niveau')
    op.drop_table('enseignement')
    op.drop_table('permission')
    op.drop_table('evaluation')
    op.drop_table('enseignant')
    op.drop_table('cycle')
    op.drop_table('user')
    op.drop_table('type_salaire')
    op.drop_table('trimestre')
    op.drop_table('serie')
    op.drop_table('section')
    op.drop_table('role')
    op.drop_table('matiere')
    op.drop_table('eleve')
    op.drop_table('appreciation')
    op.drop_table('annee')
    # ### end Alembic commands ###
