"""add_user_in_inscription_table

Revision ID: e3e6232cb9f5
Revises: 748c8b899f1d
Create Date: 2026-05-16 23:03:51.795868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3e6232cb9f5'
down_revision: Union[str, Sequence[str], None] = '748c8b899f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'classe', 'niveau', ['id_niveau'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cours', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'cours', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'cours', 'enseignant', ['id_enseignant'], ['id'])
    op.create_foreign_key(None, 'cours', 'matiere', ['id_matiere'], ['id'])
    op.create_foreign_key(None, 'cycle', 'section', ['id_section'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'discipline_eleve', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'discipline_eleve', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'discipline_eleve', 'evaluation', ['id_evaluation'], ['id'])
    op.create_foreign_key(None, 'discipline_eleve', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'enseignant', 'type_salaire', ['id_type_salaire'], ['id'])
    op.create_foreign_key(None, 'enseignement', 'matiere', ['id_matiere'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'enseignement', 'enseignant', ['id_enseignant'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'evaluation', 'trimestre', ['id_trimestre'], ['id'])
    op.create_unique_constraint(None, 'groupe_matiere', ['libelle'])
    op.create_foreign_key(None, 'groupe_matiere_evalue', 'niveau', ['id_niveau'], ['id'], ondelete='CASCADE')
    op.add_column('inscription', sa.Column('is_inscris', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('inscription', sa.Column('id_user', sa.Integer(), nullable=True))
    op.alter_column('inscription', 'date_inscris',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_foreign_key(None, 'inscription', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'inscription', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'inscription', 'user', ['id_user'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inscription', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'matiere', 'groupe_matiere', ['id_groupe_matiere'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'matiere_evalue', 'groupe_matiere_evalue', ['id_groupe_matiere'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'niveau', 'cycle', ['id_cycle'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'niveau', 'serie', ['id_serie'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'notation', 'evaluation', ['id_evaluation'], ['id'])
    op.create_foreign_key(None, 'notation', 'matiere_evalue', ['id_matiere_evalue'], ['id'])
    op.create_foreign_key(None, 'notation', 'appreciation', ['id_appreciation'], ['id'])
    op.create_foreign_key(None, 'notation', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'notation', 'classe', ['id_classe'], ['id'])
    op.create_foreign_key(None, 'notation', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'permission', 'role', ['id_role'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'presence_eleve', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'presence_eleve', 'cours', ['id_cours'], ['id'])
    op.create_foreign_key(None, 'presence_enseignant', 'enseignant', ['id_enseignant'], ['id'])
    op.create_foreign_key(None, 'presence_enseignant', 'cours', ['id_cours'], ['id'])
    op.create_foreign_key(None, 'reglement', 'tranche_pension', ['id_tranche_pension'], ['id'])
    op.create_foreign_key(None, 'reglement', 'annee', ['id_annee'], ['id'])
    op.create_foreign_key(None, 'reglement', 'eleve', ['id_eleve'], ['id'])
    op.create_foreign_key(None, 'tranche_pension', 'niveau', ['id_niveau'], ['id'])
    op.create_foreign_key(None, 'user_role', 'user', ['id_user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role', 'role', ['id_role'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'tranche_pension', type_='foreignkey')
    op.drop_constraint(None, 'reglement', type_='foreignkey')
    op.drop_constraint(None, 'reglement', type_='foreignkey')
    op.drop_constraint(None, 'reglement', type_='foreignkey')
    op.drop_constraint(None, 'presence_enseignant', type_='foreignkey')
    op.drop_constraint(None, 'presence_enseignant', type_='foreignkey')
    op.drop_constraint(None, 'presence_eleve', type_='foreignkey')
    op.drop_constraint(None, 'presence_eleve', type_='foreignkey')
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'notation', type_='foreignkey')
    op.drop_constraint(None, 'niveau', type_='foreignkey')
    op.drop_constraint(None, 'niveau', type_='foreignkey')
    op.drop_constraint(None, 'matiere_evalue', type_='foreignkey')
    op.drop_constraint(None, 'matiere', type_='foreignkey')
    op.drop_constraint(None, 'inscription', type_='foreignkey')
    op.drop_constraint(None, 'inscription', type_='foreignkey')
    op.drop_constraint(None, 'inscription', type_='foreignkey')
    op.drop_constraint(None, 'inscription', type_='foreignkey')
    op.alter_column('inscription', 'date_inscris',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('inscription', 'id_user')
    op.drop_column('inscription', 'is_inscris')
    op.drop_constraint(None, 'groupe_matiere_evalue', type_='foreignkey')
    op.drop_constraint(None, 'groupe_matiere', type_='unique')
    op.drop_constraint(None, 'evaluation', type_='foreignkey')
    op.drop_constraint(None, 'enseignement', type_='foreignkey')
    op.drop_constraint(None, 'enseignement', type_='foreignkey')
    op.drop_constraint(None, 'enseignant', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'discipline_eleve', type_='foreignkey')
    op.drop_constraint(None, 'cycle', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'cours', type_='foreignkey')
    op.drop_constraint(None, 'classe', type_='foreignkey')
    # ### end Alembic commands ###
